inputs:
  CACHIX_SIGNING_KEY:
    required: true

runs:
  using: composite
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
      with:
        extra_nix_config: |
          show-trace = true

    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: gerschtli
        signingKey: ${{ inputs.CACHIX_SIGNING_KEY }}

    - name: Build dev shell
      shell: bash
      run: nix develop --profile profile && rm profile
