inputs:
  CACHIX_SIGNING_KEY:
    required: true

runs:
  using: composite
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          show-trace = true

    - name: Setup cachix
      uses: cachix/cachix-action@v14
      with:
        name: gerschtli
        signingKey: ${{ inputs.CACHIX_SIGNING_KEY }}

    - name: Build dev shell
      shell: bash
      run: nix develop --profile profile && rm profile
